version: '3'

services:
  user_feedback_mongo:
    image: mongo
    # ports:
    #   - 27017:27017
    volumes:
      - ./data/db:/data/db
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  uf_server:
    build: ./server
    #ports:
    #  - 3000:3000
    environment:
      MONGODB_URL: mongodb://user_feedback_mongo:27017/
    restart: unless-stopped
    depends_on:
      user_feedback_mongo:
        condition: service_healthy
  
  uf_client:
    build: ./client
    #ports:
    #  - 4000:3000
    restart: unless-stopped

networks:
  default:
    name: trufi-server
